### ISSUE TITLE
Add a picture to an event: how to complete?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#104]
It is not clear for me how to upload a picture to an event. When added, it seems not te be uploaded
![picto uploaden in events](https://user-images.githubusercontent.com/75615204/102227707-2b9e5c00-3eea-11eb-8273-621b451df2df.PNG)

**Comment by ivchicano** [comment]
Related to issues #73 and #80 , the upload feature is WIP and is currently not working. At the moment to insert a picture you have to use the URL option.
I will close this issue when this feature will be implemented (Probably by today afternoon).

**Comment by ivchicano** [comment]
Implemented. Closing
