### ISSUE TITLE
Publishing toggle colour change 

### ISSUE THREAD

**Issue by Leo-Moertenhuber** [micado-eu/pa_application#106]
Hi @ivchicano & @GiuseppeCSI 

please use our main dark blue colour **#0F3A5D**  for every publishing toggle/ switch in the app

**Comment by GiuseppeCSI** [comment]
I have changed the colors on my sections, so @ivchicano can close this when he is done.
@Leo-Moertenhuber note that for disabled toggles there is a grey-out effect, so the color will look a little bit different

**Comment by ivchicano** [comment]
Changed, closing issue
