### ISSUE TITLE
select language bar update (info centre / events form)

### ISSUE THREAD

**Issue by Leo-Moertenhuber** [micado-eu/pa_application#107]
Hi @ivchicano 

due to my misunderstanding that the whole form will be translated, which is incorrect, please move the language selection bar up - below the description. (Information Centre and EVents Page) 

![language bar feedback](https://user-images.githubusercontent.com/61981568/102619645-110ff100-413d-11eb-9427-53904cedbb91.PNG)

I am sorry for the back and forth.

**Comment by ivchicano** [comment]
Moved, closed
