### ISSUE TITLE
Is there a way to give aliasses to the different tags and titles?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#110]
Is there a way to give certain alias names to a guided proces or information center fact sheet? So that people can search with a different name or a little spelling mistake? e.g. in Dutch we have at least 2 or 3 ways talk about the health care system, it could be good if the same search result comes up if they use one of those. Another way to make the search easier could be that the words show while typing as is often used in a search. ( is more a topic for the migrant app)

**Comment by gioppoluca** [comment]
Unfortunately not
