### ISSUE TITLE
Translation state button in events, information and glossary

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/pa_application#114]
The translations state button is still missing from the event, information and glossary form. It should be added and linked to the publishing logic

**Comment by ivchicano** [comment]
The translation state button is missing on every form, seems like the component isn't being detected

**Comment by GiuseppeCSI** [comment]
You're right, I just noticed that. I'll also try to look into it

**Comment by GiuseppeCSI** [comment]
I found the problem, e75c9c866fca1ea098e4a608e53afd4159a90905 should fix it.
