### ISSUE TITLE
Toggle  unpublish: there is a warning about the translations being lost

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#117]
When I would like to make a change in a published content, I need to unpublish first. When I do, there is a warning all made translations will be lost for this article.

Does this literally mean ALL translations? There will be situations PA needs to change a minor piece of information in a text, for example, a price, or a phone number, or just a typo...so one has to redo the total translation. 
Is this desirable?

**Comment by GiuseppeCSI** [comment]
Maybe we used the incorrect wording, but the warning message is just a first draft. The meaning of the message is that if you modify anything, the translation process must be redone. Let's say you have a 10 lines paragraph and need to modify one word. When you put it into edit and then send it to the translation platform, the platform will receive the modified text in your language and the old translations. Then the translators will be able to see the small edit you made and modify their translation accordingly. They do not have to start over. If you publish something during this time interval, you will only see your base language. It looks clunky, but, as you will understand, the system has no way of knowing if you just fixed a typo or completely changed the whole text. The fact that you cannot immediately publish things was also put in place to incentivize people to review the content before publishing it.

**Comment by AnneliesVerroken** [comment]
Sounds really good then ;)
Thank you so much to clarify!

Van: GiuseppeCSI [mailto:notifications@github.com]
Verzonden: dinsdag 19 januari 2021 15:19
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Toggle unpublish: there is a warning about the translations being lost (#117)


Maybe we used the incorrect wording, but the warning message is just a first draft. The meaning of the message is that if you modify anything, the translation process must be redone. Let's say you have a 10 lines paragraph and need to modify one word. When you put it into edit and then send it to the translation platform, the platform will receive the modified text in your language and the old translations. Then the translators will be able to see the small edit you made and modify their translation accordingly. They do not have to start over. If you publish something during this time interval, you will only see your base language. It looks clunky, but, as you will understand, the system has no way of knowing if you just fixed a typo or completely changed the whole text. The fact that you cannot immediately publish things was also put in place to incentivize people to review the content before publishing it.
