### ISSUE TITLE
Event: possible enhancement: add a location field?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#119]
It might be desirable to add a field for the location of the event, just as in the steps in the guided process?

**Comment by ivchicano** [comment]
We will try to have this field available before the next release

**Comment by ivchicano** [comment]
Field added,closing

**Comment by AnneliesVerroken** [comment]
Thank you Ivan, great!
I see the field in the pa app, I can fill an address, but I do not see it appear in the migrant app yet.
When I change something in the text, the change is immediately visible in the migr app, but the location is not.

Do you know why that is?
Are there specifications on how to add an address, do we have to use comma’s or spaces or…?

Have a great day,


Annelies


Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: vrijdag 22 januari 2021 9:31
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Event: possible enhancement: add a location field? (#119)


Field added,closing

**Comment by ivchicano** [comment]
The field still doesn't show in the migrants app, I will fix it when I can.
I have opened an issue to keep track of this in the migrants app repository: https://github.com/micado-eu/migrant_application/issues/125

**Comment by AnneliesVerroken** [comment]
Ok, thanks!


Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: vrijdag 22 januari 2021 12:35
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Event: possible enhancement: add a location field? (#119)


The field still doesn't show in the migrants app, I will fix it when I can.
I have opened an issue to keep track of this in the migrants app repository: micado-eu/migrant_application#125<https://github.com/micado-eu/migrant_application/issues/125>
