### ISSUE TITLE
General: warn users about required fields

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#122]
Required fields should be marked in the app and the user warned if they did not fill them out before submitting the data (and sending it to the db)

**Comment by ivchicano** [comment]
When everyone finishes marking the required fields we can close this issue

**Comment by ivchicano** [comment]
I have finished marking the required fields in the information centre, glossary and event pages

**Comment by GiuseppeCSI** [comment]
Guided processes, step manager, intervention plan and all of the data settings now have required fields. Closing
