### ISSUE TITLE
Weblate result of translations

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#134]
![buddy day](https://user-images.githubusercontent.com/75615204/109321989-10d55580-7852-11eb-819b-290951f4b7f1.png)

I get this result in some translated entries... probably not desirable ;)
https://migrants.micadoproject.eu/events/62
https://migrants.micadoproject.eu/information/170
and many more...

Also, when published, the steps seem not to show in the migrant app. This goes not only for the translated version but also for the default version in English. 

I would like to test what happens exactly when an entry is published and translated and then try to unpublish and edit again, to see how this works for the translations and what exactly is lost,  but this seems to be impossible to test. It is not possible to go back to edit state, even though the content was fully translated.

**Comment by ivchicano** [comment]
> I get this result in some translated entries... probably not desirable ;)
> https://migrants.micadoproject.eu/events/62
> https://migrants.micadoproject.eu/information/170
> and many more...

The bug in the image has been fixed. Remember to clear cache (or reload using Shift + F5 to ignore cached content).

> Also, when published, the steps seem not to show in the migrant app. This goes not only for the translated version but also for the default version in English.

About the steps, do you mean the guided process steps?

> I would like to test what happens exactly when an entry is published and translated and then try to unpublish and edit again, to see how this works for the translations and what exactly is lost, but this seems to be impossible to test. It is not possible to go back to edit state, even though the content was fully translated.

To change to the editing state, first you have to unpublish the element. A warning will show at the bottom of the screen. After pressing Yes on the warning, the content will change to editing.

**Comment by AnneliesVerroken** [comment]
I get this result in some translated entries... probably not desirable ;)
https://migrants.micadoproject.eu/events/62
https://migrants.micadoproject.eu/information/170
and many more...

> The bug in the image has been fixed. Remember to clear cache (or reload using Shift + F5 to ignore cached content).

> Thank you for fixing the bug, works indeed now!

Also, when published, the steps seem not to show in the migrant app. This goes not only for the translated version but also for the default version in English.

> About the steps, do you mean the guided process steps?

> Yes, I mean the guided process steps indeed. 
https://migrants.micadoproject.eu/processes/173
This might be a good example: in English: the steps of the guided process are not visible, in Dutch they are visible after translation.

I would like to test what happens exactly when an entry is published and translated and then try to unpublish and edit again, to see how this works for the translations and what exactly is lost, but this seems to be impossible to test. It is not possible to go back to edit state, even though the content was fully translated.

> To change to the editing state, first you have to unpublish the element. A warning will show at the bottom of the screen. After pressing Yes on the warning, the content will change to editing.

> I understand, that wasa the step that did not work friday, to be able to edit after unpublishing. I tried again today and it did work to unpublish and then edit.







•

**Comment by ivchicano** [comment]
@GiuseppeCSI please check on the guided process steps problem

**Comment by GiuseppeCSI** [comment]
@AnneliesVerroken it seems that the reason the english version didn't show up was that the english content wasn't in the translated table. Was the process youwere working on a new one or an old one? Because if it was an old one, this could have been due to the fact that some time ago steps weren't automatically published once the father process was, and this could have led to the error you saw. Could you try again by making a new process and checking if it works as intended?

**Comment by AnneliesVerroken** [comment]
I will  try with a new process today! 

I am still trying to see what happens if you want to adapt a translation after translating and publishing, but that seems hard for now. Ill also give it a new try today.
I was talking with Timo about this as well, he is not sure we will see old translations when we want to adapt something after publishing.

**Comment by AnneliesVerroken** [comment]
I am not able to log in in the PA app anymore... So cant test today.
Any solution on how to log in? I use  admin@pa.micado.eu / micadoadm2020

**Comment by gioppoluca** [comment]
@AnneliesVerroken please DO NOT POST account credentials in the open, there is a new account to be used write a mail to @GiuseppeCSI

**Comment by AnneliesVerroken** [comment]
Sure, got it

Van: Luca Gioppo [mailto:notifications@github.com]
Verzonden: maandag 8 maart 2021 8:58
Aan: micado-eu/pa_application
CC: Annelies Verroken; Mention
Onderwerp: Re: [micado-eu/pa_application] Weblate result of translations (#134)


@AnneliesVerroken<https://github.com/AnneliesVerroken> please DO NOT POST account credentials in the open, there is a new account to be used write a mail to @GiuseppeCSI<https://github.com/GiuseppeCSI>

**Comment by AnneliesVerroken** [comment]
Hi, 
I tried to make [a new GP](https://pa.micadoproject.eu/guided_process_editor/edit/206) and also an [information sheet](https://pa.micadoproject.eu/information/188/edit), to see 

• how the steps came out: **the steps published ok** 

• what happens if I try to edit again after publishing and translating?
=> 2 different outcomes:

In the [inf sheet](https://pa.micadoproject.eu/information/188/edit): 
• I tried to unpublish, clicked yes to proceed, but the toggle doesnt move at all, so I cant edit the text
Result in the migr app: english version still visible, [Dutch version](https://migrants.micadoproject.eu/information/188) is visible as an information sheet, but it is empty


[In the GP](https://pa.micadoproject.eu/guided_process_editor/edit/206): 
• It worked to unpublish, the toggle moved, the procves is not visible anymore in the migr app
• I am unable to change the status of the text to edit. 

=> so still not able to see in weblate what happens to edit a translation that was translated and published once before...

**Comment by GiuseppeCSI** [comment]
Ok, for the information sheet published toggle not working as intended I would ask for @ivchicano 's help.
About the guided process, there actually is a reason you can not change the text. Text can only be edited when the base language (in our case English) is in the translated state and, as you can see from the buttons, only the Dutch language is in the translated state as of right now. We are also talking with Timo in order to modify the process a little bit and to really make it so that the old translations are not deleted from weblate, so I would say to wait some more on that because things will be subject to change

**Comment by AnneliesVerroken** [comment]
Thank you Giuseppe!
No problem at all to wait ….
 I am sorry it took me so long to figure out what my question exactly was ;)


Van: GiuseppeCSI ***@***.***
Verzonden: vrijdag 12 maart 2021 14:28
Aan: micado-eu/pa_application
CC: Annelies Verroken; Mention
Onderwerp: Re: [micado-eu/pa_application] Weblate result of translations (#134)


Ok, for the information sheet published toggle not working as intended I would ask for @ivchicano<https://github.com/ivchicano> 's help.
About the guided process, there actually is a reason you can not change the text. Text can only be edited when the base language (in our case English) is in the translated state and, as you can see from the buttons, only the Dutch language is in the translated state as of right now. We are also talking with Timo in order to modify the process a little bit and to really make it so that the old translations are not deleted from weblate, so I would say to wait some more on that because things will be subject to change

**Comment by AnneliesVerroken** [comment]
![weblate edit text after publishing](https://user-images.githubusercontent.com/75615204/110955414-e0111800-8349-11eb-8fcf-827f3734060b.PNG)

I gave it another try with a glossary item , and this is what I got... if I see this correctly, the old translation is not lost, and indeed shows me what was edited. Anyhow, I edited, adapted the translation, it published in English but not in Dutch. In the Dutch version it shows an empty glossary item

Just to let you know ;)

**Comment by AnneliesVerroken** [comment]
Hi Ivan, I see this item is closed, does it mean all issues are fixed, does it work well now to change translations after publishing?

**Comment by ivchicano** [comment]
Sorry, I think I may have closed this issue by accident, my apologies.
Still, I have created a info sheet and made the following:
- Translate it with the translation platform
- Publish it
- Unpublish it
- Edit it
- Retranslate the edited content
- Publish it again
And I have found no issues. Please try again and if you find any issues we can reopen this.

**Comment by AnneliesVerroken** [comment]
Thank you for the answer Ivan!
What happened with the original translation? You say retranslate, you mean the translation was gone and you had to make a whole new one? Or was it possible just to adapt a little bit?
That is what we want to avoid, to have to put totally new translations all over, there will definitely be need for minor adaptations in the translations.


Thanks,

Annelies

Annelies Verroken
E-inclusie
Tel. 03 334 41 40

Atlas - integratie & inburgering Antwerpen



Op 19 apr. 2021 om 12:56 heeft Iván Chicano ***@***.***> het volgende geschreven:

﻿

Sorry, I think I may have closed this issue by accident, my apologies.
Still, I have created a info sheet and made the following:

  *   Translate it with the translation platform
  *   Publish it
  *   Unpublish it
  *   Edit it
  *   Retranslate the edited content
  *   Publish it again
And I have found no issues. Please try again and if you find any issues we can reopen this.

**Comment by ivchicano** [comment]
I have adapted the translation, just like you showed in the image when translating a glossary item

**Comment by AnneliesVerroken** [comment]
Oh great! That would be very good news!

I ll give it another try myself as well!

Annelies Verroken
E-inclusie
Tel. 03 334 41 40

Atlas - integratie & inburgering Antwerpen



Op 19 apr. 2021 om 13:06 heeft Iván Chicano ***@***.***> het volgende geschreven:

﻿

I have adapted the translation, just like you showed in the image when translating a glossary item

**Comment by AnneliesVerroken** [comment]
Jan Blonde has double-checked, seems ok, great!
