### ISSUE TITLE
Taxonomy: how to add info sheets and event sheets to the correct branches?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#138]
When adding a guided process, I can choose to add this GP to certain branches of the taxonomy. 1 or more, this is very clear.
Is the same solution possible, since these info sheets and event sheets will have to appear under the same branches, along with the guided processes? Or is it intended that we do this in another way? 

Related question: Who can set up the main taxonomy? (Categories and subcategories)? With the normal admin password I have no access to this?

**Comment by ivchicano** [comment]
We have just changed the topic selector to be the same as the one in the guided processes.

About the second question I think @gioppoluca should have the answer to this.

**Comment by AnneliesVerroken** [comment]
I see it, that is great and very clear, thank you!

A related question, why is the field "category" still relevant? I used to benecessary to filter the results in the lists, but that is no longer the case? Just a question... probably I am overlooking something.

**Comment by ivchicano** [comment]
You can still use it as a filter in the PA and NGO applications, but in the migrants app at the moment is not very useful. Maybe it can be used in the future in a filtering option in the main page of the mgirants app

**Comment by AnneliesVerroken** [comment]
Got it! Thank you
