### ISSUE TITLE
Design DB for glossary

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/pa_application#14]
Glossary have:
- title (translatable)
- description (translatable)
- language

**Comment by gortazar** [comment]
In order to draw a correspondence between the different translations of a given term of the glossary, the design would be:

Glossary:
* id

Glossary_translation:
* id
* glossary_id (FK glossary)
* title
* description
* language

**Comment by gioppoluca** [comment]
On the glossary I opted for a different model since there is not column that does not need translation and so not divided the table on a useless glossary and a glassary_translation (as you can see the other talves in the main table we have columnd like icon that have a proper meaning)
