### ISSUE TITLE
Not possible to save a GP with only a title

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#143]
to make sure we can make all internal links, we are inserting the titles first.
This works with batch upload but if you want to add one quickly, it is impossible without filling the other fields.
I noticed this is the same for info or events. 
![cannot save only a title](https://user-images.githubusercontent.com/75615204/116899374-c3051100-ac37-11eb-9530-3c6cd9b43b69.PNG)

Maybe this will become a bit uneasy in certain situations? The warning could 
be added when someone wants to publish and some fields are not filled?

**Comment by gioppoluca** [comment]
Not possible since is a test, just write dummy text, this has always been mandatory field.
We cannot remove required field check.

**Comment by AnneliesVerroken** [comment]
I understand, we are good.
 But it not as easy as putting a dummy text. If you don't have any published documents yet, you can't. 
Just saying this might cause hiccups for those who do not know the app very well.
