### ISSUE TITLE
Topics appear before publication

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#145]
When creating a new topic, it immediately appears in the related field when creating a new (glossary, information, etc.) entry, even before publishing. Does it work intentionaly like this, so that PA users can pre-select options?

**Comment by AnneliesVerroken** [comment]
I was particularly happy with this;) For me it means indeed we can preset the whole item correctly. 
It also gives the option to check if the taxonomy was entered correctly in the PA app before you publish the topics.So I hope it stays;)
