### ISSUE TITLE
Linked items in description are not rendered correctly.

### ISSUE THREAD

**Issue by trtstm** [micado-eu/pa_application#146]
When an item contains 2 or more linked items the rendering seems to go wrong. It seems to be just a frontend issue (how we convert the @[...] to actual html) since it the backend it is stored correct:
`description: "Een @[g,147](beëdigde vertaling) is een vertaling gemaakt door een beëdigd vertaler. Een beëdigd vertaler heeft een @[g,152](diploma) van een erkende vertaalopleiding en legt een professionele eed af voor een rechtbank. Een vertaling van een beëdigd vertaler is pas écht een @[g,147](beëdigde vertaling) als ze voorzien zijn van een slotformule van de vertaler, vergezeld door zijn of haar handtekening en ambtsstempel.↵↵"
`

The html that is generated is mixing up the html tags etc:
`<p>Een g,152 van een erkende vertaalopleiding en legt een professionele eed af voor een rechtbank. Een vertaling van een beëdigd vertaler is pas écht een @[g" class="mention"&gt;beëdigde vertaling als ze voorzien zijn van een slotformule van de vertaler, vergezeld door zijn of haar handtekening en ambtsstempel.</p>`

Since it IS stored properly in the backend, could we keep adding content and just ignore how it looks at the moment?

**Comment by ivchicano** [comment]
You should be able to keep adding content, this is purely a display issue

**Comment by ivchicano** [comment]
Fixed https://github.com/micado-eu/pa_application/commit/3cf749d63601bde30f5f080e33853719504620a8
