### ISSUE TITLE
Events: Add warning that start/end time are reqiured fields

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#152]
When you now save an event wihtout these two inputs, it will be not saved and the user also does not get a warning

**Comment by ivchicano** [comment]
At the top of the page there is a warning about mandatory fields, but I will add a warning when trying to save

**Comment by ivchicano** [comment]
Fixed by https://github.com/micado-eu/pa_application/commit/0dd7e838925336462d3ae91b576550733292a9e8
