### ISSUE TITLE
in "events", "time" input is unclear

### ISSUE THREAD

**Issue by janjbarski** [micado-eu/pa_application#157]
“time” doesn’t suggest that you should click on the calendar/clock icon to select date/time; when typing it in free-hand, there’s worry it won’t be saved and also what date format is right (expectation that the default formatting for “time” and “date” is shown in the box)

**Comment by ivchicano** [comment]
I think it would be fine to make the field unwrittable (readonly), but clicking on it displays the time/date selector.

**Comment by ivchicano** [comment]
Fixed https://github.com/micado-eu/pa_application/commit/a173a9b84200d31e307f549a9c3e9d61a17c9bec
