### ISSUE TITLE
Migration in figures bug

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/pa_application#161]
If there are no entry in the charts table on the db, the page shows as blank white page without the banner and the button to manage charts

**Comment by balcse** [comment]
it should work to copy a row from the joint DB and insert it via PGadmin

**Comment by GiuseppeCSI** [comment]
Yes it does, it seems that the rendering of the page (with the buttons that allow managing charts) is linked to the condition that there must be at least three boards. Is there a reason for this? Because, while putting things manually from pgadmin is a functioning workaround, i think the page should be visible and functional also without any data in it

**Comment by JowieXiang** [comment]
Thank you all for the discussion, the original code was problematic, and now I am handling the data-loading more properly:
Fix here c5fa0a49b8197cebd28252d9496f604d5fe1cf43
