### ISSUE TITLE
Event date-time bug

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/pa_application#162]
It seems that if you write the date and time manually in the event creator, you cannot save the event because the format could be incorrect. Maybe we should only allow date and time selecting via the selector and make the input field read only

**Comment by ivchicano** [comment]
Related to https://github.com/micado-eu/pa_application/issues/157

**Comment by ivchicano** [comment]
Fixed https://github.com/micado-eu/pa_application/commit/a173a9b84200d31e307f549a9c3e9d61a17c9bec
