### ISSUE TITLE
Migration in figures: Some charts are cut off

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/pa_application#173]
Some charts are shown cut off. In the following chart, it should show "Females - 52.7%" but it only shows a bit
![captura](https://user-images.githubusercontent.com/46921761/120626971-7d6c7b80-c463-11eb-8eb5-c2cf2497cbaa.png)

**Comment by balcse** [comment]
can you add a screenshot of the whole board (to see whats right to the chart)? I tried to replicate this but the labels are shown in full

**Comment by ivchicano** [comment]
The previous screenshot was from a user, but I tested it with some of the custom laptop resolutions from chrome debugging tools
![chrome_bxJrG8aYTy](https://user-images.githubusercontent.com/46921761/120776512-9db03f00-c524-11eb-849e-9af62d8c3531.png)
I will send you an email with the csv file that created this chart

**Comment by balcse** [comment]
should be fixed with 8f6b93b1161adef885df1ea2d5e50d024d33b86d but please let me know if the charts are still displayed incorrectly
