### ISSUE TITLE
Migration in figures: Selecting pie chart requires filling all fields in a bars chart

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/pa_application#174]
To be able to save a pie chart you have to select a bar chart, fill all required fields and then select pie chart. It should work only selecting pie chart.
It may be due to checking required fields for bar chart (x and y axis) in pie chart.

**Comment by balcse** [comment]
field names were misleading, they are now index column and value column and can be provided for pie-charts too (8f6b93b1161adef885df1ea2d5e50d024d33b86d)
