### ISSUE TITLE
Text in Information centre is overlapped with the tags, topics and user types

### ISSUE THREAD

**Issue by gortazar** [micado-eu/pa_application#42]
In the list of information items, the text in the Category column, spans over the other columns, hence icons and buttons appear in front of the text.

![image](https://user-images.githubusercontent.com/203272/96703023-a76ca400-1392-11eb-96a2-da9adb10c42a.png)

**Comment by gortazar** [comment]
@ivchicano can you have a look at this?

**Comment by ivchicano** [comment]
Fixed on monday
Commit: https://github.com/micado-eu/pa_application/commit/9e513e6f1652c98ae1738a69b6566c9f8fe944f5
Closing now
