### ISSUE TITLE
make the editor comply to the translation state

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/pa_application#45]
The glossaryeditor need to be readonly to allow all the forms to make the field comply with the translation button state

**Comment by gioppoluca** [comment]
linked to #44

**Comment by ivchicano** [comment]
Can't we use the GlossaryEditorViewer component?

**Comment by gioppoluca** [comment]
Yes but the glossaryeditor does not have a readonly property that places the internal components in readonly state so we need to have this property exposed.

**Comment by ivchicano** [comment]
Readonly is already done (see #44 ), if you need anything else let me know
