### ISSUE TITLE
Link to glossary not working

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/pa_application#55]
Using the custom text editor, the link to the glossary by the mean of @ does not work. For data where the @ is present, no tooltip is shown

**Comment by ivchicano** [comment]
I am currently changing the current mention system to a similar strategy that we discussed previously (mentions are looked for when loading the description instead of the PA indicating what is a mention). When this is implemented this will be fixed

**Comment by ivchicano** [comment]
Changes are already done and this problem is fixed, check the documentation I sent via email to check how to use the components now
