### ISSUE TITLE
General: Provide a short description (like 🛈 ) for relevant fields

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#67]
So that people know what is meant with board, category, etc.

**Comment by ivchicano** [comment]
@GiuseppeCSI I have seen that you started adding. Can you make a component that we can reuse in different parts of the app?

**Comment by GiuseppeCSI** [comment]
I've created a component called HelpLabel. You will need to bind the field name to the fieldLabel prop and the help text to the helpLabel prop. As usual, the text should be taken from the i18n folder
