### ISSUE TITLE
Guided processes: upload of file not possible at process step description & url upload not good visible

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/pa_application#73]
![image](https://user-images.githubusercontent.com/61241645/99066766-c59c7d00-25a9-11eb-9b1b-b0c57971a2ee.png)

Upload of file not possible.

![image](https://user-images.githubusercontent.com/61241645/99066939-1c09bb80-25aa-11eb-835e-8fd85e5c2992.png)

URL upload not visible

**Comment by HanneApers** [comment]
I experienced the same (and opened an issue for it, saw this issue only now, sorry).

**Comment by gioppoluca** [comment]
This is linked to #80

**Comment by ivchicano** [comment]
Uploading images has been implemented. Closing.
