### ISSUE TITLE
Do I need to set up an information sheet in each language separately?

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/pa_application#77]
As a PA I want to set up an information sheet for the e-learning course 'Leefloon, wat je moet weten?'.

https://rise.articulate.com/share/ZLY3uQ2rAv6lnWAT2Gr26EF4vtpUMA4a#/

Standard I do the set up in English and the InfoSheet becomes visible.

![image](https://user-images.githubusercontent.com/61241645/99143244-461bb600-265c-11eb-80b3-3c1735f14aa7.png)

If I put the same information into another language and save it the information I've put in the English section is gone. I conclude I need to setup a InfoSheet in each language separately.

I entered a InfoSheet in language Nederlands, after saving this sheet is not visible and also not visible in migrants_application where I selected language Nederlands. All infosheets in language 'English' are visible once I select language English.

![image](https://user-images.githubusercontent.com/61241645/99143433-b4ad4380-265d-11eb-8f36-4c0c3c86d72d.png)

**Comment by ivchicano** [comment]
This is indeed a bug, you should be able to save an element in different languages from the same add new element page. It seems it is not saving the element in languages different from the default one.

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/99273547-78c6d980-2829-11eb-80d1-230cf825112d.png)

Bug is still present...I first entered English and then German...result is that English content was not visible anymore...only the German content...without seeing the actual content...

**Comment by ivchicano** [comment]
It seems the tag for that element didn't save correctly, I will look into it (for the moment I deleted all bugged tags). Try reloading the page and trying again, for the tests I made I can't seem to find any more bugs.

**Comment by ivchicano** [comment]
Tags have been removed, so this no longer applies. Closing.
