### ISSUE TITLE
weblink using URL box gives non-info icon - information centre functionality

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/pa_application#79]
![image](https://user-images.githubusercontent.com/61241645/99272535-318c1900-2828-11eb-9be3-90fee8d0aa7c.png)

If I use the url box to insert an URL it gives the non-info-box of a wrong link...

If I then just paste the weblink it becomes visible.

Why isn't a proper link tot the content visibl if I use the weblink box?

**Comment by ivchicano** [comment]
The box is suposed to be for inserting images, where you can upload (currently WIP) or use an URL to an image to insert it.
You can insert an URL simply writing or pasting it into the editor, no button is needed.
