### ISSUE TITLE
Create new layout for PA application

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/pa_application#8]
We need the color schema and overall design of the PA application.
This need to be nice to look but also has to be with colors that to not contrast with any potential colors of the PA logo (a minimalistic approach is always better)

The application will be a desktop browser application so even if we will use a PWA approach  the design will have to target a monitor and not a smart phone.

In this case the user will be mother tongue, no need to have translations, the application will be localized so please take into account different length of text in different languages.

We can use lass images even if a nice image help the overall appeal of the application.

Probably the actual layout could be a good one, we need a proper placement of content in toolbar, footer, sidebar etc.

The application will have to be accessed ONLY after login.

We need to be able to accomodate logo of PA that could have different colours.

**Comment by gioppoluca** [comment]
We keep PA stuff in this issue:
https://micado.hcu-hamburg.de/nextcloud/apps/drawio/118616

My feedbacks on the PA navigation:
- I'm not a big fan of pages where we find different type of content together like the "Info editor overview page"; since in the menu we have the 2 submenu of the general info and process info I would create a dedicated page for each entity to manage
- some entities like "glossary" and "general info" could be designed as a master/detail appreoach since the amount of information to write is little; other like the "process info" could be more complicated
- on the "process info" you asre forgetting that we have also to manage the required document list that is a management that require its own specific approach so probably we need to rethink all the design of this part
- you are missing "glossary", document types, "task types"

Logically I would divide the main menu into something more clear by usage:
- there are things that I would call settings, that you do rarely, possibly at the first implant of the application like defining "glossary", "document types", "task types", "setting the logo, activating the features
- there are editing of elements that could be done periodically like "general info" (that I do not like as name since are much more news or information that could evolve in time - at least some), processes
- I would have a user management menu element especially for the NGO, not sure for the migrants
- we need a menu for operational activities like assigning task to a migrant

On user management we do not plan to have migrant user management since migrant will self register, we could have a generic administration of a registration, but I doubt that a PA user will manage migrant users; we need to ask to John if he needs to get the information on the given consent for a single migrant, in this case we could have a search page with limited administration goals, but we need to remember that migrants do not have a mail so there is difficult in password recovery

NGO user management instead is more complicated and the proposed apporach is correct, but there is not the master detail for adding the NGO entity and than the admin role (the PA will not add the users of NGO, just add the admin role and than it will be that user that will manage users of the NGO from the NGO application): we do not want to burden PA users with this management.

Also we need to understand if NGO need to have consent management since they will be people treating the data and not adding personal data, in that case there could be the need to have the NGO admin to check some approval on the first access.

**Comment by gioppoluca** [comment]
I think that we could need a "migrant status" page where I can search for a migrant and see its "integration status" how is he going on with the tasks, some information of him and the documents list he has.

Could we also add some notes from PA on the subject?

The option to send messages?

**Comment by gioppoluca** [comment]
@JowieXiang here you find some feedbacks

**Comment by gioppoluca** [comment]
Another feedback is that we could need pages for uploading data in the system (like migrants data from the central anagraphic system, or other data)

At the moment we do not know the exact data, but I'm expecting to upload a CSV file and getting the feedback on the result.

**Comment by JowieXiang** [comment]
Hi Luca, thank you very much for the feedback. I have made adjustments accordingly.
https://micado.hcu-hamburg.de/nextcloud/apps/drawio/118616
