### ISSUE TITLE
I can't add information to the information centre or events

### ISSUE THREAD

**Issue by HanneApers** [micado-eu/pa_application#81]
I tried to add information in the Dutch section. When I press 'save' it doesn't do anything. 

Other remarks: 
- text editing is very basic and not user-friendly: the text font is very large and can't be adapted, if I want to put something in **bold**, I always have to scroll up to hit the bold-button; it is not possible to insert tables nor bulleted lists (which would facilitate and structure the presentation of information); I can only use full tabs to go to the next line, leaving a lot of interlining space, etc. Will this be adapted in the final version or will it remain as basic as now? 
- Why is the text limited to 800 characters and the title only 20? It forces me to delete essential information to just 'make it fit'.
- I can't seem to add categories or I don't know how. Basic instructions on how to add things like these would be useful. On the other hand: will everyone just be able to make categories? Should the app not provide some structural categories?

**Comment by ivchicano** [comment]
I can answer about the text limits, which are a bug as this limitations should only apply to the glossary. This will be fixed (be aware however that a limit will still exist).

For the text editor options I have to ask @Leo-Moertenhuber , should we have the formatting options menu bar on the bottom side of the editor? Should we allow more options? Should these options be dependent of the page or shared across all instances of the editor (such as glossary, information centre, guided processes...)?

For creating categories go to the information centre (or events page) and click the categories button on the top right corner.

![chrome_pWlyWTHs1m](https://user-images.githubusercontent.com/46921761/99642042-557b7480-2a4b-11eb-862a-0d763aeb0288.png)

Only the PA can create, edit or delete categories. I'm not sure what you mean by structural categories.

**Comment by ivchicano** [comment]
About trying to add an element and not showing, when adding an element in the PA app it will only show the default language translation (at the moment English). If you don't provide a translation in this language it will not show. In a future change we will explicitly ask for a translation in the default language. Sorry for the inconvenience

**Comment by HanneApers** [comment]
Okay, that clarifies a lot, thanks for your answer! 
With structural categories, I mean predefined categories, because if every PA can 'invent' categories it might become a mixture of different wordings for what can potentially be categorized under one word (for instance: 'inscription', 'enrollment', 'application' could all refer to the same, but are then three different categories). But this might be something content-related, that has to be discussed within a country team.
Just to make you aware: I made a printscreen on how the page looks on my laptop (using Google Chrome), which lay-out is clearly 'messier' than in the image you provided:

![image](https://user-images.githubusercontent.com/49522075/99644095-c9b71780-2a4d-11eb-888e-624e9b7c57af.png)

**Comment by ivchicano** [comment]
Thanks for the screenshot, I wil ltry to fix these issues of it being so messy.

For predefined or default categories I have to ask for @gioppoluca 's opinion, but I think it is not that good of an idea because of what you said (this default categories can be different for every country or even different public administrations)

**Comment by HanneApers** [comment]
Thanks! Yes, I understand, I agree that it might not be good to set default categories, as this might be too specific.

**Comment by ivchicano** [comment]
At the moment the text limits and the buttons not displaying correctly on smaller viewports have been fixed, and when adding an element it asks for a default language translation.

**Comment by Leo-Moertenhuber** [comment]
Regarding the sparse formatting options for the text - I think we can/ should discuss this in our upcoming call. At the moment we chose to have very few options (only bold and Italics) because it makes it easier for the translation tool we are using. If adding more options like bulletpoints/ tables is doesn´t come with issues from a development point of view, it should be no problem to add these options.

**Comment by ivchicano** [comment]
Closing this issue now as the changes to text limits and bugs. The issue related to the position of the menu bar in the editor is related to #88 , the decision of having only bold, italics and images was made to avoid making translation of the content harder.
