### ISSUE TITLE
Information center & events: takes too long to load every time the feature is activated

### ISSUE THREAD

**Issue by JowieXiang** [micado-eu/pa_application#84]
Suggestions: 
1. use frontend cache (can refer to settings or migration monitor)
2. use lazy loading

**Comment by ivchicano** [comment]
Optimizations have to be made to these pages.
- Too many requests are being made (almost 3 requests per element is just wrong)
- Pagination should be added

I will also look into cache or lazy loading, but we run the risk of the content not being updated when displaying it.

**Comment by ivchicano** [comment]
Load times have been improved by commit https://github.com/micado-eu/pa_application/commit/7db9d27303b3fddccfedd39fe84c48ad1584fd1c

**Comment by ivchicano** [comment]
Closing for now, if it is still too slow we should reopen this issue or open a new one
