### ISSUE TITLE
Information Centre - Check "Add Information" & "Edit Information" Form

### ISSUE THREAD

**Issue by Leo-Moertenhuber** [micado-eu/pa_application#88]
Hi @ivchicano - below is a list of my proposed updates 

Updates for both Forms: 
- let's move the disclaimer "Please fill the default language.." centered and above the title field so its the first thing the user will see
- please add the indicator for the maximum number of characters (50) to the title, above the input field at the right side
- regarding the last comments for the Info centre I moved the text formatting options below the input field 
- please add the "translation bar" below the description filed, aligned with the right end of the text field
- I would propose a separate "image Upload" section since I feel we need to separate text formatting and image uploads
- we need the gray background for all input fields to have a coherent design, so tags, category, topic and user type should have the same gray background inside the input field as it as at the title and description 

https://www.figma.com/file/i2iikyHbwCfngbNETXqHPK/MICADO-Migrant-APP---look-%26-feel?node-id=78%3A20

If anything is unclear let me know

**Comment by ivchicano** [comment]
Some considerations:
- Tags are going to be removed
- How do we manage multiple images in the same text? The images are attached to the description. Also I think it should be closer to the editor because the image will be attached at the position of the cursor inside the editor.

**Comment by Leo-Moertenhuber** [comment]
- I think its a good idea to remove the tags since the icons are getting a bit too much - which means I will redo the mockup 
- I think I misunderstood because I thought the images will be separated from the text, but as you described it here this isn´t the idea. This means the thought of moving the image upload away from the text editor is heading in the wrong direction. 

i am not sure if I understood correctly but here would be my idea for multiple images + using the cursor
-  is it possible to add images with a right mouseclick inside the text editor? If so, we could have the info of how to place an image just as a tooltip over the current "upload image" icon and then the user could move the cursor where he wants to place the image and just add it with right-click -> add image

**Comment by ivchicano** [comment]
I will try to add the option to the right click menu

**Comment by Leo-Moertenhuber** [comment]
Thank you - I will update the mockup in the meantime

**Comment by ivchicano** [comment]
I can't add the image to the right click menu without losing all other options (like cut, copy, paste...). An alternative I propose is the one used in here: https://tiptap.dev/floating-menu

**Comment by Leo-Moertenhuber** [comment]
That is a great alternative - but unfortunately, I see 2 issues at the moment 

- it seems that it is only possible to add an image with a URL. What do we do when the user wants to select an image stored offline on their computer?
- I thought about this the last few days and I am not 100% sure if it makes sense to add the images directly into the text. What would you think of the idea from my latest mockup update. Which is to add images like they are in an email? with attachments after the text ends. 
(my thought is that if bulletpoints/ etc makes it harder for our translation tool, images will probably as well?)

**Comment by ivchicano** [comment]
- If you click on the current image button on the text formatting options a dialog will open that lets you choose between uploading from your computer or writing an url. When image uploading is fully implemented the upload from computer option will work.
- I think it is a good idea, but it might require too much effort to make for the little time we have, so I would keep it like it is right now and discuss this in a further release.

**Comment by Leo-Moertenhuber** [comment]
- I misunderstood. I thought the example you sent will be exactly how it will be in the micado app. When we can keep both the URL and the image upload from the computer then I have no issues with it at all. 
- ah, thank you for the clarification. As I sadly have no background in development it is hard for me to get a feeling how much work something like the images below the text would take to implement. In this case, I fully agree and with you. 

thank you very much for finding the alternative option, let's go along with this version.

As usual I will update the mockups accordingly

**Comment by ivchicano** [comment]
All the changes are done (except the images one), please double check if everything is correct: http://pa.micadoproject.eu/information/new

**Comment by Leo-Moertenhuber** [comment]
Looks really nice!  One minor detail and then I think we are all good. 

Please add the same padding between the last to rows of input fields as above. So that "select category" and and "topics & types" have the same empty space above and below them as the title and the description. 

![Infor centre form - feedback](https://user-images.githubusercontent.com/61981568/101780848-5c9c1c80-3af7-11eb-97fe-0fbe7842ea08.png)
