### ISSUE TITLE
How to use the TranslateStateButton component

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/pa_application#90]
Looking to implement the translation state in my pages I saw that you were using a TranslateStateButton to change the state of translation.
To avoid duplication I was thinking of using this component, but I can't find any documentation or how to use it.
Thanks in advance.

**Comment by GiuseppeCSI** [comment]
You should indeed use the component, but unfortunately there is no documentation on it yet. 
The gist of it would be the following:
You import the compontent (you can see the full component in the ngo app) and the translationbutton mixin, and then set up the following:
v-model:the translation state of your entity;
isForDefaultLanguage: decides for which language the button can be used,  must be true for the active language of the app and false for the others
objectId: the id of your entity
readonly: disables the button for the other languages, must be false for active language of the app and true for the others,
@micado-change: the button fires a micado change event, which in turn calls a method with two parameters. The first is your current entity, and the second is the state of the button(which represent the translation state). The method will update all of your entity's translation states to the one of the button.

Having said that, I think you can just copy it from, for example, the edit process page and substitute your entity in v-model, objectId and the first parameter of the method. The rest of the stuff should be pretty much the same.

**Comment by ivchicano** [comment]
Thanks for the help, closed
