### ISSUE TITLE
Information Centre: Add more filters

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#92]
Provide more filter possibilities (e.g. region, on-/offline, ages, etc.

**Comment by ivchicano** [comment]
I think we should discuss this in the next call. Maybe the PA could be able to create Key/Value elements that would show in the filters? (kind of like tags but more powerful).
Also, remember that the search bar allows for searching elements, it checks the title and the description of the element, so it is pretty useful if the information to search is there.
