### ISSUE TITLE
Event: not possible to edit a newly added event

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#96]
The newly added event "Buddy day" can not be edited. I can open the edit page for other events but not for this event.

![Edit event not loading](https://user-images.githubusercontent.com/75615204/101624124-c47c3580-3a19-11eb-9fd1-b2fbedd39f29.PNG)

**Comment by ivchicano** [comment]
The issue should be fixed now, please double check if you still can't edit the event.

**Comment by AnneliesVerroken** [comment]
just checked, still not possible

**Comment by ivchicano** [comment]
Is this your event? http://pa.micadoproject.eu/events/51/edit
I am able to edit it as seen in the image, please try clearing the cache from your browser.
![chrome_uWrYJIIlhT](https://user-images.githubusercontent.com/46921761/101640817-4592f700-3a31-11eb-88d9-1a58c3b0a053.png)

**Comment by AnneliesVerroken** [comment]
Hi, yes , that is it.

I have cleared cache and still have the same problem, I will try it later today on another computer and different browser.




Annelies Verroken
Medewerker E-inclusie

Atlas - Integratie en Inburgering Antwerpen



________________________________
Van: Iván Chicano <notifications@github.com>
Verzonden: woensdag 9 december 2020 15:15:09
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Event: not possible to edit a newly added event (#96)


Is this your event? http://pa.micadoproject.eu/events/51/edit
I am able to edit it as seen in the image, please try clearing the cache from your browser.
[chrome_uWrYJIIlhT]<https://user-images.githubusercontent.com/46921761/101640817-4592f700-3a31-11eb-88d9-1a58c3b0a053.png>

**Comment by AnneliesVerroken** [comment]
Works!

Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: woensdag 9 december 2020 15:15
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Event: not possible to edit a newly added event (#96)


Is this your event? http://pa.micadoproject.eu/events/51/edit
I am able to edit it as seen in the image, please try clearing the cache from your browser.
[chrome_uWrYJIIlhT]<https://user-images.githubusercontent.com/46921761/101640817-4592f700-3a31-11eb-88d9-1a58c3b0a053.png>

**Comment by ivchicano** [comment]
Thanks, closing this issue then
